CREATE TABLE user_app(
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	age int4 NOT NULL,
	fone varchar(255) NOT NULL,
	specificid varchar(1000) NULL,
	loan_specificid varchar(1000) NULL,

    CONSTRAINT user_app_pkey PRIMARY KEY (id)
);