CREATE TABLE book(
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(255) NOT NULL,
	resume varchar(500) NOT NULL,
	isbn varchar(255) NOT NULL,
	author varchar(255) NOT NULL,
	year_book date NULL,
	specificid varchar(1000) NULL,
	loan_specificid varchar(1000) NULL,
	status boolean NOT NULL,

    CONSTRAINT book_pkey PRIMARY KEY (id)
);